<div class="card">

    <div class="card-header">
        <h2 class="m-0">Lista de Motoristas</h2>
    </div>

    <div class="card-body">

        <table class="table table-striped table-bordered">
            <tr>
                <th>Nome</th>
                <th>RG</th>
                <th>CPF</th>
                <th>Telefone</th>
                <th>Veículo</th>
                <th></th>
            </tr>

            <?php foreach ($motoristas as $motorista): ?>
                <tr>
                    <td><?= $motorista->getNome(); ?></td>
                    <td><?= $motorista->getRg(); ?></td>
                    <td><?= $motorista->getCpf(); ?></td>
                    <td><?= $motorista->getTelefone(); ?></td>
                    <td>
                        <a href="<?= $this->url('veiculos', ['action' => 'editar', 'id' => $motorista->getVeiculo()->getId()]); ?>"
                        <?= $motorista->getVeiculo()->getPlaca() ?>
                      </a>
                    </td>
                    <td class="text-center">
                        <a class="btn btn-outline-warning" href="<?= $this->url('driver', ['action' => 'editar', 'id' => $motorista->getId()]); ?>">EDITAR</a>
                        <a class="btn btn-outline-danger" onclick="return confirm('Deseja realmente excluir esse motorista?')" href="<?= $this->url('motoristas', ['action' => 'deletar', 'id' => $motorista->getId()]); ?>">EXCLUIR</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
  <a href="<?= $this->url('motoristas', ['action' => 'cadastrar']); ?>" class="btn btn-primary">Cadastrar Motorista</a>
</div>